# Generated by Django 2.2 on 2022-12-22 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('urls', models.CharField(max_length=50, null=True, unique=True)),
                ('users', models.ManyToManyField(related_name='components', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
