# Generated by Django 2.2 on 2022-12-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DF_Components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentmodel',
            name='users',
        ),
    ]
