# Generated by Django 2.2 on 2022-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DF_Components', '0002_remove_componentmodel_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFlowComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('urls', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ComponentModel',
        ),
    ]
