# Generated by Django 2.2 on 2022-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DF_Components', '0003_auto_20221222_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflowcomponent',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
