# Generated by Django 2.2 on 2022-12-23 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DF_Components', '0004_auto_20221222_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflowcomponent',
            name='users',
            field=models.ManyToManyField(related_name='components', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DF_Components.DataFlowComponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
