# Generated by Django 2.2 on 2022-12-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcessing', '0002_auto_20221203_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settarget_column',
            name='set_target_column',
            field=models.CharField(max_length=30),
        ),
    ]
