# Generated by Django 2.2 on 2022-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcessing', '0005_auto_20221203_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settarget_column',
            name='set_target_column',
            field=models.CharField(choices=[('PassengerId', 'PassengerId'), ('Survived', 'Survived'), ('Pclass', 'Pclass'), ('Name', 'Name'), ('Sex', 'Sex'), ('Age', 'Age'), ('SibSp', 'SibSp'), ('Parch', 'Parch'), ('Ticket', 'Ticket'), ('Fare', 'Fare'), ('Cabin', 'Cabin'), ('Embarked', 'Embarked')], max_length=30),
        ),
    ]
