# Generated by Django 2.2 on 2022-12-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcessing', '0006_auto_20221203_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='setTarget_column',
        ),
    ]
