# Generated by Django 4.1.2 on 2022-10-28 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="upload_Dataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_statement_type",
                    models.CharField(
                        choices=[
                            ("Regression", "Regression"),
                            ("Classification", "Classification"),
                            ("Clustering", "Clustering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("problem_statement_name", models.CharField(max_length=40, null=True)),
                (
                    "problem_statement_description",
                    models.TextField(blank=True, max_length=75, null=True),
                ),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="./uploads/"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
