# Generated by Django 2.2 on 2022-12-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngestion', '0006_auto_20221230_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_dataset',
            name='import_sources',
        ),
        migrations.RemoveField(
            model_name='upload_dataset',
            name='name',
        ),
        migrations.CreateModel(
            name='import_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('import_sources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='dataIngestion.importSources')),
            ],
        ),
        migrations.AddField(
            model_name='upload_dataset',
            name='import_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataIngestion.import_Data'),
        ),
    ]
