# Generated by Django 2.2 on 2023-01-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngestion', '0007_auto_20221230_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_dataset',
            name='import_data',
        ),
        migrations.AddField(
            model_name='upload_dataset',
            name='file_from_resources',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
