# Generated by Django 2.2 on 2023-03-01 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngestion', '0008_auto_20230102_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_dataset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
